### ISSUE TITLE
Asari innate biotics

### ISSUE THREAD

**Issue by TheMarmotKing** [queryluke/masseffect-5e#405] opened 2019-04-11 23:31 UTC
The asari innate biotics gives Access to vanguard abilities, a few of which rely on barrier to use.

**Comment by queryluke** [comment] 2019-04-12 02:32
I see. So the issue is that, say, an asari soldier takes innate biotics and chooses something like barrier detonation. Though I see the issue, I think this is more resolved with player choice than system changes. But it's a really good point. I'll have to noodle it for a while.

**Comment by TheMarmotKing** [comment] 2019-04-12 03:07
That's exactly what happened lol. Played a one shot with my players, they had a blast.  My infiltrator wanted me to tell you he loves the sniper subclass

**Closed** 2019-08-16 11:13 UTC
